api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Nginx server"
  homepage = "https://github.com/paketo-buildpacks/nginx"
  id = "paketo-buildpacks/nginx"
  keywords = ["nginx", "server", "distribution"]
  name = "Paketo Buildpack for Nginx Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.21.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nginx:nginx:1.21.5:*:*:*:*:*:*:*"
    id = "nginx"
    licenses = ["BSD-2-Clause"]
    name = "Nginx Server"
    purl = "pkg:generic/nginx@1.21.5?checksum=b20f3bf533a518a6f0f3a7967dfeed872d268d31e4cc121a0001329602ddcfbb&download_url=http://nginx.org/download/nginx-1.21.5.tar.gz"
    sha256 = "1690ed3774774a2d5f117d4648171683885c6bbe962fc29b628183e48999867e"
    source = "http://nginx.org/download/nginx-1.21.5.tar.gz"
    source_sha256 = "b20f3bf533a518a6f0f3a7967dfeed872d268d31e4cc121a0001329602ddcfbb"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/nginx/nginx_1.21.5_linux_x64_bionic_1690ed37.tgz"
    version = "1.21.5"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nginx:nginx:1.21.6:*:*:*:*:*:*:*"
    id = "nginx"
    licenses = ["BSD-2-Clause"]
    name = "Nginx Server"
    purl = "pkg:generic/nginx@1.21.6?checksum=66dc7081488811e9f925719e34d1b4504c2801c81dee2920e5452a86b11405ae&download_url=http://nginx.org/download/nginx-1.21.6.tar.gz"
    sha256 = "739ec0ac0ee83b8e8fd044d9b9313f226deac16157a2574ec035d9f8fa5c044d"
    source = "http://nginx.org/download/nginx-1.21.6.tar.gz"
    source_sha256 = "66dc7081488811e9f925719e34d1b4504c2801c81dee2920e5452a86b11405ae"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/nginx/nginx_1.21.6_linux_x64_bionic_739ec0ac.tgz"
    version = "1.21.6"

  [[metadata.dependency-constraints]]
    constraint = "1.21.*"
    id = "nginx"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.22.*"
    id = "nginx"
    patches = 2
  [metadata.version-lines]
    mainline = "1.21.*"
    stable = "1.22.*"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
